import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// The {children} property (curly braces indicate object restructuring) in the function parameter
//    is being extracted from the object that is passed as an argument to the RootLayout component.
// By using children in the function parameter, it assigns the value of the children property to a variable named children
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
